### ISSUE TITLE
No .pre-commit-config.yaml file was found

### ISSUE THREAD

**Issue by brianpursley** [BountyStrike/Bountystrike-sh#16]
I tried to follow the instructions for contribution where it says to run `pre-commit install`, but when I try to commit, I get this message:
```
No .pre-commit-config.yaml file was found
- To temporarily silence this, run `PRE_COMMIT_ALLOW_NO_CONFIG=1 git ...`
- To permanently silence this, install pre-commit with the --allow-missing-config option
- To uninstall pre-commit run `pre-commit uninstall`
```

Is there a .pre-commit-config.yaml that is supposed to be included in the repo?

**Comment by dubs3c** [comment]
No, my fault. I copied the install instructions from another project where this was included. That part should be removed from the readme.

**Comment by dubs3c** [comment]
Fixed in https://github.com/BountyStrike/Bountystrike-sh/commit/6f32dcc3581dec3b830051aaa330f111b320e36a
