### ISSUE TITLE
Running amass in the background fucks up terminal

### ISSUE THREAD

**Issue by enthroned** [BountyStrike/Bountystrike-sh#3]
I tried to run the script for testing purposes but the amass process fucked up my terminal.

**Comment by dubs3c** [comment]
Same happened to me, amass just freezes. Doesn't work either when just running the command :/ Investigating...

I wonder if amass simply hangs if something goes wrong internally.

**Comment by dubs3c** [comment]
I am getting this error: https://github.com/OWASP/Amass/issues/315

Maybe the solution is to give amass a bunch of other resolvers to try

**Comment by dubs3c** [comment]
Meh, can find a good solution for it, so added a timeout for amass, if it does not complete within 2 minutes it will be killed. Check it out in this branch: https://github.com/BountyStrike/Bountystrike-sh/tree/feature/cli
